### ISSUE TITLE
Doc build error!

### ISSUE THREAD

**Issue by DavidJohnGee** [StackStorm/ipfabric-docs#56]
. virtualenv/bin/activate; sphinx-build -W -b html docs/source docs/build/html
Error: Config directory doesn't contain a conf.py file.
make: *** [docs] Error 1

**Comment by LindsayHill** [comment]
Ah, that's because we like to lead a more complicated life.

These docs don't exist on their own. They're meant to be an add-on/update to the base st2docs. To build a local copy of bwc-docs.brocade.com (rather than just docs.stackstorm.com), clone st2docs, and run `make bwclocaldocs` or `make bwclivedocs` - that should pull down the ipfabric docs, copy them into place, update some template stuff, and build all the docs.
