### ISSUE TITLE
runner_type_list is not described in BWC RBAC docs at all. 

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/ipfabric-docs#77]
https://bwc-docs.brocade.com/rbac.html#available-permission-types

I think with this, we also need some examples in contrib/rbac which should be shipped with packages so people can use that as a reference.

**Comment by Kami** [comment]
Yeah, probably need to update Makefile or similar since this table is auto-generated as part of st2docs build, but it's possible that the Makefile step which does that was copied over to ipfabric-docs Makefile.

**Comment by LindsayHill** [comment]
The script that runs is this one: https://github.com/StackStorm/st2docs/blob/master/scripts/generate-available-permission-types-table.py

It only lives in the st2docs repo, and it generates content for both. Because of the way the docs are built, the script is only called from the st2docs Makefile. It gets called for both `make docs` and `make bwcdocs`. 

Looks like it might be as simple as adding RUNNER_TYPE here https://github.com/StackStorm/st2docs/blob/master/scripts/generate-available-permission-types-table.py#L34

Will do some tests, and submit PR

**Comment by LindsayHill** [comment]
Actually, looks like a few changes to https://github.com/StackStorm/st2/blob/master/st2common/st2common/rbac/types.py#L360 needed

```
(virtualenv) ubuntu@st2expect:~/st2docs$ ./scripts/generate-available-permission-types-table.py
Traceback (most recent call last):
  File "./scripts/generate-available-permission-types-table.py", line 80, in <module>
    main()
  File "./scripts/generate-available-permission-types-table.py", line 64, in main
    description = PermissionType.get_permission_description(permission_type)
  File "/home/ubuntu/st2docs/st2/st2common/st2common/rbac/types.py", line 172, in get_permission_description
    description = PERMISION_TYPE_TO_DESCRIPTION_MAP[permission_type]
KeyError: 'runner_type_list'
(virtualenv) ubuntu@st2expect:~/st2docs$
```

I'll take a stab at that PR first.

**Comment by LindsayHill** [comment]
@lakshmi-kannan I've created a couple of PRs https://github.com/StackStorm/st2/issues/3324 and https://github.com/StackStorm/st2docs/issues/447 that should address this. Can you review those?
